### PR TITLE
Search fix

### PR DESCRIPTION
**Pull request by Maxi10022**
Fixed the issue when searching for GE to no longer include the status column.
Which in turn fixes the issue where a invariant item would be found.
Updated the InventoryNumberComparer, this should fix any issue when sorting by id.

### CODE REVIEW

**Comment by tomblair7254** [comment]
Not sure how to merge your changes with my code. Can you help;?

**Comment by Maxi10022** [comment]
Can you add me to your collaborators then I can merge it for you. 
You have to go to https://github.com/tomblair7254/FieldMRIServices/settings/access and send me a collaboration invite, my username is Maxi10022.

**Comment by tomblair7254** [comment]
Ok is done thanks

**Comment by Maxi10022** [comment]
Thanks, its merged you can now use pull to get the current version from here on GitHub.

**Pull request merged**
