### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Maxi10022**

### CODE REVIEW

**Comment by tomblair7254** [comment]
The sort function no longer works.

 

From: Maximilian Hollnbuchner ***@***.***> 
Sent: Saturday, December 14, 2024 10:47 AM
To: tomblair7254/FieldMRIServices ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomblair7254/FieldMRIServices] Updates (PR #4)

 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/tomblair7254/FieldMRIServices/pull/4


Commit Summary


*	0221401 <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/022140199781f61d0908976d823c02264102f72b>  Merge pull request #1 from Maxi10022/search-fix
*	f5153e1 <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/f5153e1366798159ed0bc86da291e7c2f22a3c6e>  Refactored InventoryNumberComparer
*	2f17d0f <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/2f17d0f39ea36788fd55bb5165dcd1cb32988a31>  Update MedicalInventory.razor
*	7c7052d <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/7c7052d8f47bd3b811a1e4ee7c43b3da53d40f76>  Added ISortableModel
*	c2bbbc2 <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/c2bbbc214d032b51c24843ec2eb42af8070b6e99>  Updated InventoryNumberComparer
*	9adf9bf <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/9adf9bf0e45d47b9066df39f2cb8a1c2feb96325>  Updated ComputerModel.cs and InventoryModel.cs
*	c0090cd <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/c0090cdb7aec4c3c938383679156c4a16164c84b>  Fixed sorting for the ComputerInventory.razor
*	8240505 <https://github.com/tomblair7254/FieldMRIServices/pull/4/commits/8240505188d98ae0e6c1d7d9614a750846d540af>  Added styles for styling the horizontal scroll bar


File Changes 


(7 <https://github.com/tomblair7254/FieldMRIServices/pull/4/files>  files)

*	M Comparers/InventoryNumberComparer.cs <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-967a7170ca50886caea31ba73341a38d43419c1d62bc275fb657d5911a5dbe78>  (38) 
*	A Models/Abstractions/ISortableModel.cs <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-9bdf838884d0f07e1c4d9afa441fac461e8ecbf8c69ef3d6da7bdf6b8f9a308c>  (6) 
*	M Models/ComputerModel.cs <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-1cd6737046a16d0684a6e616b2d6fe0bf1aafa95f4f73c4c67ffa64959abf0ca>  (4) 
*	M Models/InventoryModel.cs <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-a885a25d039f24bf9b845aaf008747892af4e02af3267fd481e40cfeaf5dd668>  (3) 
*	M Pages/ComputerInventory.razor <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-0c9d93479eac536483c8a9a78b2a9b22a713b23ed8e0c053e6a5e029407b038b>  (42) 
*	M Pages/MedicalInventory.razor <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-4fd4bd5a5b0d938b6d69a8a63cf1cfb669e316fb95ad3c110df5d806e883b147>  (13) 
*	M wwwroot/css/site.css <https://github.com/tomblair7254/FieldMRIServices/pull/4/files#diff-a3395c619d2932c6a78cdd9a018c00daf39c06c44622de8726964591322f3e7e>  (29) 


Patch Links:


*	https://github.com/tomblair7254/FieldMRIServices/pull/4.patch
*	https://github.com/tomblair7254/FieldMRIServices/pull/4.diff

**Comment by Maxi10022** [comment]
Sorry for the oversight, its now fixed.

**Comment by tomblair7254** [comment]
Looks good is there a way to have the bottom scroll bar always show while scroll up and down?

**Comment by Maxi10022** [comment]
I think this should be possible but I would have to look a little bit into it. 
For clarity, do you want the scrollbar which scrolls the table horizontally, to be outside of the current box, fixed at the bottom of the screen?

**Comment by tomblair7254** [comment]
Yes that is what I would like if this is possible?

**Comment by Maxi10022** [comment]
Yes this is possible, I will send you message once I implemented it.

**Pull request merged**
